Repository redis/NRedisStack, pull requests merged in 2023-01, with the labels that each got.

#57 Support for BF.CARD
  src/NRedisStack/Bloom/BloomCommandBuilder.cs
  src/NRedisStack/Bloom/BloomCommands.cs
  src/NRedisStack/Bloom/IBloomCommands.cs
  src/NRedisStack/Bloom/Literals/Commands.cs
  tests/NRedisStack.Tests/Bloom/BloomTests.cs
Labels: feature

#56 Increasing code coverage
  src/NRedisStack/Graph/DataTypes/Edge.cs
  src/NRedisStack/Graph/DataTypes/GraphEntity.cs
  src/NRedisStack/Graph/DataTypes/Node.cs
  src/NRedisStack/Graph/DataTypes/Path.cs
  src/NRedisStack/Graph/GraphCacheList.cs
  src/NRedisStack/Graph/GraphCommandBuilder.cs
  src/NRedisStack/Graph/GraphCommands.cs
  src/NRedisStack/Graph/Header.cs
  src/NRedisStack/Graph/IGraphCommands.cs
  src/NRedisStack/Graph/Point.cs
  src/NRedisStack/Graph/Record.cs
  src/NRedisStack/Graph/RedisGraphUtilities.cs
  src/NRedisStack/Json/JsonCommandBuilder.cs
  src/NRedisStack/Json/JsonCommands.cs
  src/NRedisStack/Search/AggregationRequest.cs
  src/NRedisStack/Search/AggregationResult.cs
  src/NRedisStack/Search/DataTypes/InfoResult.cs
  src/NRedisStack/Search/DataTypes/SearchInformation.cs
  src/NRedisStack/Search/Document.cs
  src/NRedisStack/Search/Extensions/IndexDataTypeExtensions.cs
  src/NRedisStack/Search/FTCreateParams.cs
  src/NRedisStack/Search/FieldName.cs
  src/NRedisStack/Search/Group.cs
  src/NRedisStack/Search/Literals/Enums/IndexDataType.cs
  src/NRedisStack/Search/Query.cs
  src/NRedisStack/Search/Reducer.cs
  src/NRedisStack/Search/Reducers.cs
  src/NRedisStack/Search/SearchCommands.cs
  src/NRedisStack/Search/SearchResult.cs
  src/NRedisStack/Search/SortedField.cs
  src/NRedisStack/TimeSeries/Extensions/AggregationExtensions.cs
  src/NRedisStack/TimeSeries/Extensions/BucketTimestampsExtensions.cs
  src/NRedisStack/TimeSeries/Extensions/ReduceExtensions.cs
  src/NRedisStack/TopK/TopKCommandBuilder.cs
  tests/NRedisStack.Tests/Bloom/BloomTests.cs
  tests/NRedisStack.Tests/CuckooFilter/CuckooTests.cs
  tests/NRedisStack.Tests/Graph/GraphTests.cs
  tests/NRedisStack.Tests/Search/SearchTests.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestRange.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestRangeAsync.cs
  tests/NRedisStack.Tests/TopK/TopKTests.cs
Labels: maintenance

#59 Delete pre-release icon
  README.md
Labels: maintenance

#67 Ignore case on spellcheck
  .github/spellcheck-settings.yml
Labels: maintenance

#72 Wrong argument count in VectorField
  src/NRedisStack/Search/Schema.cs
  tests/NRedisStack.Tests/Search/SearchTests.cs
Labels: bug

#76 Adding a README to the nuget package
  .github/workflows/integration.yml
  src/NRedisStack/NRedisStack.csproj
Labels: maintenance
