Repository redis/NRedisStack, pull requests merged in 2023-07, with the labels that each got.

#145 Support Triggers and Functions
  src/NRedisStack/Gears/GearsCommandBuilder.cs
  src/NRedisStack/Gears/GearsCommands.cs
  src/NRedisStack/Gears/GearsCommandsAsync.cs
  src/NRedisStack/Gears/Literals/CommandArgs.cs
  src/NRedisStack/Gears/Literals/Commands.cs
  src/NRedisStack/ResponseParser.cs
  tests/NRedisStack.Tests/Gears/GearsTests.cs
Labels: feature, docs-review

#155 Escape backslashes in RedisGraphUtilities.PrepareQuery
  src/NRedisStack/Graph/GraphCommandBuilder.cs
  src/NRedisStack/Graph/RedisGraphUtilities.cs
  tests/NRedisStack.Tests/Graph/GraphTests.cs
Labels: bug

#151 Add support for extended search commands
  Examples/AdvancedJsonExamples.md
  Examples/AdvancedQueryOperations.md
  Examples/BasicJsonExamples.md
  Examples/BasicQueryOperations.md
  README.md
  src/NRedisStack/Pipeline.cs
  src/NRedisStack/ResponseParser.cs
  src/NRedisStack/Search/FTSpellCheckParams.cs
  src/NRedisStack/Search/ISearchCommands.cs
  src/NRedisStack/Search/ISearchCommandsAsync.cs
  src/NRedisStack/Search/Literals/CommandArgs.cs
  src/NRedisStack/Search/Literals/Commands.cs
  src/NRedisStack/Search/Query.cs
  src/NRedisStack/Search/SearchCommandBuilder.cs
  src/NRedisStack/Search/SearchCommands.cs
  src/NRedisStack/Search/SearchCommandsAsync.cs
  src/NRedisStack/Transactions.cs
  tests/NRedisStack.Tests/Search/SearchTests.cs
Labels: feature, docs-review, breakingchange

#158 Delete Unnecessary Tests
  tests/NRedisStack.Tests/Bloom/BloomTests.cs
  tests/NRedisStack.Tests/CountMinSketch/CmsTests.cs
  tests/NRedisStack.Tests/CuckooFilter/CuckooTests.cs
  tests/NRedisStack.Tests/Graph/GraphTests.cs
  tests/NRedisStack.Tests/Json/JsonTests.cs
  tests/NRedisStack.Tests/Search/SearchTests.cs
  tests/NRedisStack.Tests/Tdigest/TdigestTests.cs
  tests/NRedisStack.Tests/TimeSeries/TimeSeriesTests.cs
  tests/NRedisStack.Tests/TopK/TopKTests.cs
Labels: maintenance

#159 adding hash examples
  tests/Doc/HashExample.cs
  tests/Doc/SearchQuickstartExample.cs
  tests/Doc/SetGetExample.cs
Labels: maintenance
