Repository redis/NRedisStack, pull requests merged in 2023-09, with the labels that each got.

#178 Split TFCALL to TFCALL and TFCALLASYNC
  src/NRedisStack/Gears/GearsCommands.cs
  src/NRedisStack/Gears/GearsCommandsAsync.cs
  src/NRedisStack/Graph/IGraphCommands.cs
  src/NRedisStack/Graph/IGraphCommandsAsync.cs
  tests/NRedisStack.Tests/Gears/GearsTests.cs
Labels: feature, experimental

#177 Deprecate RedisGraph
  src/NRedisStack/Graph/IGraphCommands.cs
  src/NRedisStack/Graph/IGraphCommandsAsync.cs
Labels: maintenance

#182 Update README
  .github/wordlist.txt
  README.md
Labels: maintenance

#170 Initial support for OSS Cluster API
  .github/cluster.env
  .github/docker-compose.yml
  .github/dockers/Dockerfile.cluster
  .github/dockers/cluster.redis.conf
  .github/dockers/create_cluster.sh
  .github/standalone.env
  .github/workflows/integration.yml
  .github/workflows/reusable.yml
  CONTRIBUTING.md
  src/NRedisStack/Auxiliary.cs
  tests/Doc/Doc.csproj
  tests/Doc/HashExample.cs
  tests/Doc/SearchQuickstartExample.cs
  tests/Doc/SetGetExample.cs
  tests/NRedisStack.Tests/AbstractNRedisStackTest.cs
  tests/NRedisStack.Tests/Bloom/BloomTests.cs
  tests/NRedisStack.Tests/CountMinSketch/CmsTests.cs
  tests/NRedisStack.Tests/CuckooFilter/CuckooTests.cs
  tests/NRedisStack.Tests/Examples/ExampleTests.cs
  tests/NRedisStack.Tests/Gears/GearsTests.cs
  tests/NRedisStack.Tests/Graph/GraphTests.cs
  tests/NRedisStack.Tests/Json/JsonTests.cs
  tests/NRedisStack.Tests/PipelineTests.cs
  tests/NRedisStack.Tests/RedisFixture.cs
  tests/NRedisStack.Tests/Search/SearchTests.cs
  tests/NRedisStack.Tests/SkipIfRedisAttribute.cs
  tests/NRedisStack.Tests/SkipIfRedisVersionAttribute.cs
  tests/NRedisStack.Tests/Tdigest/TdigestTests.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestAdd.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestAlter.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestCreate.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestDecrBy.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestDel.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestGet.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestIncrBy.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestMADD.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestMAddAsync.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestMGet.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestMGetAsync.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestMRange.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestMRangeAsync.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestMRevRange.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestMRevRangeAsync.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestQueryIndex.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestQueryIndexAsync.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestRange.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestRangeAsync.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestRules.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestRulesAsync.cs
  tests/NRedisStack.Tests/TimeSeries/TimeSeriesTests.cs
  tests/NRedisStack.Tests/TopK/TopKTests.cs
  tests/NRedisStack.Tests/TransactionsTests.cs
Labels: feature

#189 Disabling multiple runs of a PR based on commit
  .github/workflows/doctests.yml
  .github/workflows/integration.yml
  .github/workflows/spellcheck.yml
Labels: maintenance

#183 Lint checks in CI runs
  .github/workflows/linter.yaml
  CONTRIBUTING.md
  tests/NRedisStack.Tests/Search/SearchTests.cs
  tests/NRedisStack.Tests/SkipIfRedisAttribute.cs
  tests/NRedisStack.Tests/TopK/TopKTests.cs
  tests/NRedisStack.Tests/TransactionsTests.cs
Labels: maintenance
