Repository redis/NRedisStack, pull requests merged in 2023-05, with the labels that each got.

#120 Testing against multiple redis-stack versions
  .github/workflows/integration.yml
Labels: maintenance

#125 Update Version to 0.6.1
  src/NRedisStack/NRedisStack.csproj
Labels: maintenance

#127 Change TimeStamp from DateTime to Millisecond Instead of Ticks
  src/NRedisStack/TimeSeries/DataTypes/TimeStamp.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestAdd.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestAddAsync.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestMADD.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestMAddAsync.cs
  tests/NRedisStack.Tests/TimeSeries/TestDataTypes/TestTimeStamp.cs
Labels: bug

#132 Support JSON.MERGE Command
  src/NRedisStack/Json/DataTypes/KeyValuePath.cs
  src/NRedisStack/Json/IJsonCommands.cs
  src/NRedisStack/Json/IJsonCommandsAsync.cs
  src/NRedisStack/Json/JsonCommandBuilder.cs
  src/NRedisStack/Json/JsonCommands.cs
  src/NRedisStack/Json/JsonCommandsAsync.cs
  src/NRedisStack/Json/Literals/Commands.cs
  tests/NRedisStack.Tests/Json/JsonTests.cs
Labels: feature

#137 issue template
  .github/ISSUE_TEMPLATE.md
Labels: maintenance

#139 Fix JSON.MERGE Summary
  src/NRedisStack/Json/IJsonCommands.cs
  src/NRedisStack/Json/IJsonCommandsAsync.cs
Labels: documentation
