Repository redis/NRedisStack, pull requests merged in 2023-10, with the labels that each got.

#192 Creating CODEOWNERS for documentation
  .github/CODEOWNERS
Labels: maintenance

#193 Linking to Redis learning resources
  README.md
Labels: maintenance

#191 Support GEOSHAPE field type in RediSearch
  Examples/GeoShapeQueryExample.md
  src/NRedisStack/NRedisStack.csproj
  src/NRedisStack/Search/Query.cs
  src/NRedisStack/Search/Schema.cs
  tests/Doc/Doc.csproj
  tests/NRedisStack.Tests/Examples/ExampleTests.cs
  tests/NRedisStack.Tests/NRedisStack.Tests.csproj
  tests/NRedisStack.Tests/Search/SearchTests.cs
Labels: documentation, feature

#187 Pass in JsonSerializerOptions to generic methods
  src/NRedisStack/Json/IJsonCommands.cs
  src/NRedisStack/Json/IJsonCommandsAsync.cs
  src/NRedisStack/Json/JsonCommands.cs
  src/NRedisStack/Json/JsonCommandsAsync.cs
  tests/NRedisStack.Tests/Json/JsonTests.cs
Labels: feature

#180 Support CLIENT SETINFO Command
  src/NRedisStack/Auxiliary.cs
  src/NRedisStack/CoreCommands/CoreCommandBuilder.cs
  src/NRedisStack/CoreCommands/CoreCommands.cs
  src/NRedisStack/CoreCommands/CoreCommandsAsync.cs
  src/NRedisStack/CoreCommands/Enums/SetInfoAttr.cs
  src/NRedisStack/CoreCommands/Literals/CommandArgs.cs
  src/NRedisStack/CoreCommands/Literals/Commands.cs
  src/NRedisStack/Graph/IGraphCommands.cs
  tests/NRedisStack.Tests/Core Commands/CoreTests.cs
Labels: feature

#194 Version 0.10.0
  src/NRedisStack/NRedisStack.csproj
  tests/NRedisStack.Tests/PipelineTests.cs
  tests/NRedisStack.Tests/TransactionsTests.cs
Labels: maintenance

#196 Fix library versioning: reading version from assembly
  src/NRedisStack/Auxiliary.cs
  src/NRedisStack/NRedisStack.csproj
Labels: bug

#197 set_tutorial snippets
  tests/Doc/StringSnippets.cs
Labels: maintenance
