Repository redis/NRedisStack, pull requests merged in 2023-03, with the labels that each got.

#87 Convert SearchResult to JSON
  Examples/ConvertSearchResultToJson.md
  src/NRedisStack/Search/SearchResult.cs
  tests/NRedisStack.Tests/Examples/ExamplesTests.cs
Labels: documentation, feature

#89 Target .NET Standard 2.0
  .github/workflows/integration.yml
  src/NRedisStack/Graph/Header.cs
  src/NRedisStack/Json/JsonCommands.cs
  src/NRedisStack/Json/JsonCommandsAsync.cs
  src/NRedisStack/NRedisStack.csproj
  src/NRedisStack/ResponseParser.cs
  src/NRedisStack/Tdigest/TdigestCommands.cs
  tests/NRedisStack.Tests/Examples/ExamplesTests.cs
  tests/NRedisStack.Tests/NRedisStack.Tests.csproj
  tests/NRedisStack.Tests/Search/SearchTests.cs
  tests/NRedisStack.Tests/Tdigest/TdigestTests.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestMADD.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestMAddAsync.cs
Labels: feature

#92 Adding redis version compatibility details to the README
  .github/wordlist.txt
  README.md
Labels: maintenance

#94 Update to the Latest StackExchage.Redis Version
  src/NRedisStack/NRedisStack.csproj
  tests/NRedisStack.Tests/NRedisStack.Tests.csproj
Labels: maintenance

#101 Fix AlterAdd Test Failure
  tests/NRedisStack.Tests/Examples/ExamplesTests.cs
  tests/NRedisStack.Tests/Search/SearchTests.cs
Labels: maintenance
