Repository redis/NRedisStack, pull requests merged in 2024-03, with the labels that each got.

#261 Switch to public Redis Enterprise for CI
  .github/workflows/integration.yml
Labels: maintenance

#257 Async blocking commands
  src/NRedisStack/CoreCommands/CoreCommandBuilder.cs
  src/NRedisStack/CoreCommands/CoreCommands.cs
  src/NRedisStack/CoreCommands/CoreCommandsAsync.cs
  src/NRedisStack/CoreCommands/DataTypes/RedisStreamEntries.cs
  src/NRedisStack/CoreCommands/DataTypes/StreamSpecialIds.cs
  src/NRedisStack/CoreCommands/Literals/CommandArgs.cs
  src/NRedisStack/CoreCommands/Literals/Commands.cs
  src/NRedisStack/ResponseParser.cs
  tests/NRedisStack.Tests/Core Commands/CoreTests.cs
Labels: feature

#252 Test binary package in CI
  .github/workflows/reusable.yml
  PackageVerification/PackageVerification.cs
  PackageVerification/PackageVerification.csproj
Labels: maintenance

#259 Fix AggregationRequest Builder
  src/NRedisStack/Search/AggregationRequest.cs
  src/NRedisStack/Search/Literals/CommandArgs.cs
  src/NRedisStack/Search/Schema.cs
  tests/NRedisStack.Tests/Search/SearchTests.cs
Labels: breakingchange

#263 Update Version to 0.12.0
  src/NRedisStack/NRedisStack.csproj
Labels: maintenance

#241 Enhance code readability
  src/NRedisStack/Auxiliary.cs
  src/NRedisStack/Bloom/BloomAux.cs
  src/NRedisStack/Bloom/BloomCommandBuilder.cs
  src/NRedisStack/Bloom/BloomCommands.cs
  src/NRedisStack/Bloom/BloomCommandsAsync.cs
  src/NRedisStack/Bloom/IBloomCommands.cs
  src/NRedisStack/Bloom/IBloomCommandsAsync.cs
  src/NRedisStack/CoreCommands/CoreCommandBuilder.cs
  src/NRedisStack/CoreCommands/CoreCommands.cs
  src/NRedisStack/CountMinSketch/CmsCommandBuilder.cs
  src/NRedisStack/CountMinSketch/CmsCommands.cs
  src/NRedisStack/CountMinSketch/CmsCommandsAsync.cs
  src/NRedisStack/CuckooFilter/DataTypes/CuckooInformation.cs
  src/NRedisStack/Json/DataTypes/KeyValuePath.cs
  src/NRedisStack/Json/IJsonCommands.cs
  src/NRedisStack/Json/IJsonCommandsAsync.cs
  src/NRedisStack/Json/JsonCommandBuilder.cs
  src/NRedisStack/Json/JsonCommands.cs
  src/NRedisStack/Json/JsonCommandsAsync.cs
  src/NRedisStack/Json/Literals/CommandArgs.cs
  src/NRedisStack/Search/AggregationRequest.cs
  src/NRedisStack/Search/AggregationResult.cs
  src/NRedisStack/Search/DataTypes/InfoResult.cs
  src/NRedisStack/Search/Document.cs
  src/NRedisStack/Search/Literals/AttributeOptions.cs
  src/NRedisStack/Search/Literals/CommandArgs.cs
  src/NRedisStack/Search/Literals/Commands.cs
  tests/Doc/HashExample.cs
  tests/Doc/SearchQuickstartExample.cs
  tests/Doc/SetGetExample.cs
  tests/Doc/StringSnippets.cs
  tests/NRedisStack.Tests/AbstractNRedisStackTest.cs
  tests/NRedisStack.Tests/Examples/ExampleTests.cs
  tests/NRedisStack.Tests/Person.cs
  tests/NRedisStack.Tests/PipelineTests.cs
  tests/NRedisStack.Tests/RedisFixture.cs
  tests/NRedisStack.Tests/TransactionsTests.cs
Labels: maintenance

#264 Updating the release drafter to the latest standard^C
  .github/release-drafter-config.yml
Labels: maintenance
