Repository redis/NRedisStack, pull requests merged in 2024-08, with the labels that each got.

#295 Change InfoResult::Attributes Returned Value to Array of Arrays
  src/NRedisStack/Search/DataTypes/InfoResult.cs
  tests/NRedisStack.Tests/Examples/ExampleTests.cs
  tests/NRedisStack.Tests/Search/SearchTests.cs
Labels: bug, breakingchange

#305 test dialect 5
  tests/NRedisStack.Tests/Search/SearchTests.cs
Labels: feature

#329 fix ts.create UNCOMPRESSED set to false explicitly
  src/NRedisStack/TimeSeries/Literals/CommandArgs.cs
  src/NRedisStack/TimeSeries/TimeSeriesParamsBuilder.cs
  tests/NRedisStack.Tests/TimeSeries/TestAPI/TestCreate.cs
Labels: bug

#330 DOC-4093 HGET/HSET command code samples
  tests/Doc/CmdsHashExample.cs
Labels: documentation
